In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [22]:
#load builtind data
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [23]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [24]:
# first we creat data frame from dictionary
df = pd.DataFrame(np.c_[data.data,data.target],columns = [list(data.feature_names)+['target']])

In [25]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [26]:
# to split data into x and y
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]
print("shape of the x data :",x.shape)
print('shape of the y data :',y.shape)

shape of the x data : (569, 30)
shape of the y data : (569,)


In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state =51)
print("shape of the x_train data :",x_train.shape)
print('shape of the y_train data :',y_train.shape)
print("shape of the x_test data :",x_test.shape)
print('shape of the y_test data :',y_test.shape)

shape of the x_train data : (455, 30)
shape of the y_train data : (455,)
shape of the x_test data : (114, 30)
shape of the y_test data : (114,)


# Train svm classification model

# import svmc class


In [28]:
from sklearn.svm import SVC
#creat object of the modele
cls_rbf = SVC(kernel='rbf')
#train model
cls_rbf.fit(x_train,y_train)
#predict model
y_predict=cls_rbf.predict(x_test)
y_predict

C:\Users\ATTA UR RAHMAN\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
cls_rbf.score(x_test,y_test)

0.6666666666666666

# Feature scalling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [31]:
#apply stander scale funtion on train data
x_train_sc = sc.transform(x_train)
x_test_sc = sc.transform(x_test)

In [32]:
#creat object of the modele
cls_rbf2 = SVC(kernel='rbf')
#train model
cls_rbf2.fit(x_train_sc,y_train)
#Score of the model
cls_rbf2.score(x_test_sc,y_test)

0.9473684210526315

In [33]:
# after scaling data the above same algorithm result is good from non-scal data

# svc karnal is poly

In [45]:
# now traing model with new karnal polynomial
#creat object of the modele
cls_poly2 = SVC(kernel='poly',degree=1)
#train model
cls_poly2.fit(x_train_sc,y_train)
#Score of the model
cls_poly2.score(x_test_sc,y_test)

0.9473684210526315

# svc with karnal linear

In [46]:
# now traing model with new karnal polynomial
#creat object of the modele
cls_karnal = SVC(kernel='linear',degree=1)
#train model
cls_karnal.fit(x_train_sc,y_train)
#Score of the model
cls_karnal.score(x_test_sc,y_test)

0.9473684210526315

# predict unknown values

In [80]:
row_1=x.iloc[425]
patient1 = row_1
patient1

mean radius                 10.030000
mean texture                21.280000
mean perimeter              63.190000
mean area                  307.300000
mean smoothness              0.081170
mean compactness             0.039120
mean concavity               0.002470
mean concave points          0.005159
mean symmetry                0.163000
mean fractal dimension       0.064390
radius error                 0.185100
texture error                1.341000
perimeter error              1.184000
area error                  11.600000
smoothness error             0.005724
compactness error            0.005697
concavity error              0.002074
concave points error         0.003527
symmetry error               0.014450
fractal dimension error      0.002411
worst radius                11.110000
worst texture               28.940000
worst perimeter             69.920000
worst area                 376.300000
worst smoothness             0.112600
worst compactness            0.070940
worst concav

In [81]:
#scale the first record
patient1_sc = sc.transform(np.array([patient1]))
patient1_sc

array([[-1.15974803,  0.41929422, -1.184797  , -0.99117506, -1.08523179,
        -1.26463   , -1.11187351, -1.16045634, -0.68110196,  0.15891558,
        -0.81188963,  0.17522735, -0.84401721, -0.62977321, -0.45520669,
        -1.10806981, -0.96810822, -1.33198363, -0.74816056, -0.53391462,
        -1.08022224,  0.49385298, -1.12530604, -0.89824288, -0.85572244,
        -1.18264086, -1.25828771, -1.36975067, -0.89347242, -0.20787949]])

In [83]:
pred_pat = cls_karnal.predict(patient1_sc)
pred_pat

array([1.])

In [71]:
#predict unknown value of the test data
cls_karnal.predict(x_test_sc)

array([1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
# actual values of the test data
y_test.tail(1)

425    1.0
Name: (target,), dtype: float64

In [74]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')