In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
data = pd.read_csv(r'E:\BI\atta\Python_visulization\practice\Ml algorithms\svm\bangalore house price prediction OHE-data.csv')


In [2]:
data.shape

(7120, 108)

In [3]:
data.head(1)

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   

   location_Tumkur Road  
0                     0  

[1 rows x 108 columns]

In [4]:
x = data.drop('price',axis=1)
y = data['price']
print('shape of the x is :',x.shape)
print('shape of the y is :',y.shape)

shape of the x is : (7120, 107)
shape of the y is : (7120,)


In [5]:
#splt data for training and spliting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
print('shape of the x_train is :',x_train.shape)
print('shape of the y_train is :',y_train.shape)
print('shape of the x_test is :',x_test.shape)
print('shape of the y_test is :',y_test.shape)

shape of the x_train is : (5696, 107)
shape of the y_train is : (5696,)
shape of the x_test is : (1424, 107)
shape of the y_test is : (1424,)


# Decision Tree Regression ML model

In [6]:
#train moel with with mean squre error
from sklearn.tree import DecisionTreeRegressor
reg_model = DecisionTreeRegressor(criterion='mse')
reg_model.fit(x_train,y_train)


DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [7]:
#test the score of the model
reg_model.score(x_test,y_test)

0.9787454946085759

In [8]:
#predicted value of the testing data
reg_model.predict(x_test)

array([120. , 198. ,  70. , ...,  56.1,  54. ,  36. ])

In [9]:
#actual values of the test data
y_test.tail()

6332    59.8
3648    36.0
2036    55.0
6585    54.0
4022    36.0
Name: price, dtype: float64

In [10]:
#x_test.iloc[-1,:]

In [11]:
#predict the last value of the test data using loc function
predicted  = reg_model.predict([x_test.iloc[-1,:]])
print('predicted value is ',predicted,'of the last record')


predicted value is  [36.] of the last record


In [12]:
#actual value of 
y_test.iloc[-1]


36.0

In [13]:
#predict the second last value of the test data 
pre = x_test.iloc[-2,:]

In [14]:
reg_model.predict([pre])

array([54.])

In [15]:
y_test.iloc[-2]

54.0

In [16]:
#predict the multiple values of the test data set
reg_model.predict(x_test.head(10))

array([120. , 198. ,  70. ,  56. ,  37. ,  57.5, 145. ,  76.3,  47. ,
       115. ])

In [17]:
y_test.head(10)

6260    120.0
3881    200.0
3416     70.0
3557     56.0
6465     36.0
4477     57.6
6758    146.0
5006     75.0
1272     47.0
764     115.0
Name: price, dtype: float64

# predicte value using any index and compare with actual value

In [25]:
predicted = reg_model.predict([x_test.iloc[70,:]])
actual = y_test.iloc[70]
print('actual value is : ',actual)
print("predicted value is : ",predicted)

actual value is :  90.0
predicted value is :  [89.5]
