In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv(r'E:\BI\atta\Python_visulization\practice\Ml algorithms\svm\bangalore house price prediction OHE-data.csv')
#E:\BI\atta\Python_visulization\practice\Ml algorithms\svm\bangalore house price prediction OHE-data.csv
    

In [3]:
data.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [4]:
# to split data into x and y
x = data.drop('price',axis=1)
y = data['price']
print("shape of the x data :",x.shape)
print('shape of the y data :',y.shape)

shape of the x data : (7120, 107)
shape of the y data : (7120,)


In [5]:
#to split data for train and testing 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 51)
#to print the shape of the train and test data
print("shape of the x_train data :",x_train.shape)
print('shape of the y_train data :',y_train.shape)
print("shape of the x_test data :",x_test.shape)
print('shape of the y_test data :',y_test.shape)

shape of the x_train data : (5696, 107)
shape of the y_train data : (5696,)
shape of the x_test data : (1424, 107)
shape of the y_test data : (1424,)


# feature scalling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

# To Train Support Vector Regression

In [9]:
#import svr model
from sklearn.svm import SVR
# to creat object of the model
svr_rbf = SVR(kernel='rbf')
#to train model
svr_rbf.fit(x_train,y_train)
#test the score of the model
svr_rbf.score(x_test,y_test)

0.20638035840828173

In [12]:
# to train model as linear instead of rbf
svr_l = SVR(kernel='linear')
#to train model
svr_l.fit(x_train,y_train)
#test the score of the model
svr_l.score(x_test,y_test)

0.796272530851755

In [14]:
# now train model as poly instead of linear
svr_p = SVR(kernel='poly',degree=3)
#to train model
svr_p.fit(x_train,y_train)
#test the score of the model
svr_p.score(x_test,y_test)

0.3039932069927378

# So the accuracy of the linear svm is best we will predict test data on using linear model

In [15]:
#to predict the price of the first row 
svr_l.predict([x_test[0]])

array([86.53673464])

In [17]:
# to predict all the values for the train test datset
y_predict = svr_l.predict(x_test)
y_predict

array([ 86.53673464,  33.70390806, 122.48356838, ...,  26.23978753,
        64.52634655, 176.17532793])

In [24]:
#actual value are the below and above are the predictive values
y_test.head()

2435     80.0
3113     40.0
426     120.0
1124     79.0
1161     45.0
Name: price, dtype: float64

In [25]:
#now find vv importan root mean square
from sklearn.metrics import mean_squared_error
#mean square error
mse = mean_squared_error(y_test,y_predict)
#root mean square error
rmse = np.sqrt(mse)
print('mean squre error',mse)
print('root mean square error ',rmse)

mean squre error 4093.4831852475745
root mean square error  63.9803343633618


# so the error margin is very high let do this with linear reqration

In [27]:
#import linear regration model
from sklearn.linear_model import LinearRegression
l_model = LinearRegression()
l_model.fit(x_train,y_train)
l_model.score(x_test,y_test)

0.7903837092682254

In [33]:
# so both algo have same score
#predictied values and acutal values are below
l_model.predict(x_test)
#predictive

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [34]:
#actual values
y_test.head()

2435     80.0
3113     40.0
426     120.0
1124     79.0
1161     45.0
Name: price, dtype: float64